name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: YinCheng0106
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Taipei
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_languages: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: YinCheng0106
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_leetcode: yes
          plugin_leetcode_user: yincheng0106
          plugin_leetcode_sections: solved, skills, recent